# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CptViewer
                                 A QGIS plugin
 View Cpt files with QGis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-05
        copyright            : (C) 2022 by LeveeLogic
        email                : leveelogic@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CptViewer class from file CptViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cpt_viewer import CptViewer
    return CptViewer(iface)
